package models

// Adjustment kinds of the reconciliation adjustment item generated by ReconcileRecognizedReceiptItems
const (
	RECOGNIZED_RECEIPT_ADJUSTMENT_KIND_TAX     = "tax"
	RECOGNIZED_RECEIPT_ADJUSTMENT_KIND_UNKNOWN = "unknown"
)

// RecognizedReceiptDetailsResult represents the result of recognized receipt image with item details
type RecognizedReceiptDetailsResult struct {
	RecognizedTransactionResult
	Items    []*RecognizedReceiptItemResult   `json:"items,omitempty"`
	Merchant *RecognizedReceiptMerchantResult `json:"merchant,omitempty"`
}

// RecognizedReceiptItemResult represents one recognized receipt item line
type RecognizedReceiptItemResult struct {
	Name     string `json:"name,omitempty"`     // item name as printed on the receipt
	Amount   string `json:"amount,omitempty"`   // item amount as printed (string, same format as the top-level amount), negative for discounts
	Category string `json:"category,omitempty"` // category name chosen from the options list
}

// RecognizedReceiptMerchantResult represents the recognized merchant info of the receipt
type RecognizedReceiptMerchantResult struct {
	Name    string `json:"name,omitempty"`    // merchant name (e.g. セブン-イレブン)
	Branch  string `json:"branch,omitempty"`  // branch name (e.g. 渋谷駅前店)
	Address string `json:"address,omitempty"` // address exactly as printed
}

// RecognizedReceiptDetailsResponse represents a view-object of recognized receipt image response with item details
type RecognizedReceiptDetailsResponse struct {
	RecognizedTransactionResponse
	Items       []*RecognizedReceiptItemResponse   `json:"items,omitempty"`
	GeoLocation *TransactionGeoLocationResponse    `json:"geoLocation,omitempty"`
	Location    *RecognizedReceiptLocationResponse `json:"location,omitempty"`
}

// RecognizedReceiptItemResponse represents a view-object of one recognized receipt item
type RecognizedReceiptItemResponse struct {
	CategoryId     int64  `json:"categoryId,string,omitempty"`
	Amount         int64  `json:"amount"`            // amount ×100 (same as sourceAmount), negative for discounts; zero is meaningful (free items), so no omitempty
	Comment        string `json:"comment,omitempty"` // item name (adjustment items keep this empty, the frontend names them via i18n)
	IsAdjustment   bool   `json:"isAdjustment,omitempty"`
	AdjustmentKind string `json:"adjustmentKind,omitempty"` // "tax" (estimated exclusive tax) / "unknown" (recognition difference)
}

// RecognizedReceiptLocationResponse represents a view-object of the resolved merchant location label
type RecognizedReceiptLocationResponse struct {
	DisplayName string `json:"displayName"`
	Confidence  string `json:"confidence"` // "high" / "low"
	Provider    string `json:"provider,omitempty"`
}

// ReconcileRecognizedReceiptItems reconciles the recognized receipt items with the recognized total amount
// so that the sum of the returned items always equals the returned total amount (sum invariant).
// All amounts are integers ×100, no floating point arithmetic is used.
// When the total amount is missing (zero), the items are trusted and the item sum becomes the total amount.
// When the total amount differs from the item sum, an adjustment item is appended, labeled "tax" if the
// difference looks like an exclusive 8%-10% japanese consumption tax (±2 yen tolerance), otherwise "unknown"
func ReconcileRecognizedReceiptItems(transactionType TransactionType, totalAmount int64, items []*RecognizedReceiptItemResponse) (int64, []*RecognizedReceiptItemResponse) {
	var itemAmountSum int64

	for i := 0; i < len(items); i++ {
		itemAmountSum += items[i].Amount
	}

	if totalAmount == 0 {
		return itemAmountSum, items
	}

	delta := totalAmount - itemAmountSum

	if delta == 0 {
		return totalAmount, items
	}

	adjustmentKind := RECOGNIZED_RECEIPT_ADJUSTMENT_KIND_UNKNOWN

	if transactionType == TRANSACTION_TYPE_EXPENSE && delta > 0 && itemAmountSum > 0 {
		lowerBound := itemAmountSum*8/100 - 200       // floor(sum * 8%) - 2 yen (amounts are ×100)
		upperBound := (itemAmountSum*10+99)/100 + 200 // ceil(sum * 10%) + 2 yen (amounts are ×100)

		if lowerBound <= delta && delta <= upperBound {
			adjustmentKind = RECOGNIZED_RECEIPT_ADJUSTMENT_KIND_TAX
		}
	}

	reconciledItems := make([]*RecognizedReceiptItemResponse, 0, len(items)+1)
	reconciledItems = append(reconciledItems, items...)
	reconciledItems = append(reconciledItems, &RecognizedReceiptItemResponse{
		Amount:         delta,
		IsAdjustment:   true,
		AdjustmentKind: adjustmentKind,
	})

	return totalAmount, reconciledItems
}
